logistic_regression:
  solver: ['liblinear']
  max_iter: [5000]

random_forest:
  n_estimators: [100, 200]
  max_depth: [5, 10, 20, 50]

gradient_boosting:
  n_estimators: [50, 100, 200]
  learning_rate: [0.01, 0.1, 0.2]

svc:
  C: [1, 10, 100]
  kernel: ['linear', 'rbf', 'poly']

knn:
  n_neighbors: [10, 20]
  weights: ['uniform', 'distance']

mlp:
  hidden_layer_sizes: [[64], [128], 256, [64,64], [64,128,64], [128,256,128]]
  activation: ['relu', 'tanh', 'logistic']
  learning_rate_init: [0.001, 0.01, 0.1]
  alpha: [0.0001, 0.001, 0.01]